# vim: set expandtab ts=2 sw=2:
---
unit-test:
  stage: test
  tags:
    - beaker
  script:
    - bundle install
    - bundle exec rake spec
acceptance-test:
  stage: test
  tags:
    - docker
  image: ruby:2.1
  script:
    - bundle install
    - bundle exec rake acceptance
