HOSTS:
  server5:
    roles:
      - server
      - master
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant

  server4:
    roles:
      - client
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
  # vb_gui: true
